### ISSUE TITLE
Validators: Need indian ID validators

### ISSUE THREAD

**Issue by SwapnilSoni1999** [SwapnilSoni1999/express-dry#5]
The following regex validators are needed.

- [x] ~~PAN~~ (Completed in #8)
- [x] ~~Aadhaar~~ (Completed in #8)
- [x] ~~Driving License~~ (Completed in #9)

**RULES**
- in `validators/` add `_IN` as postfix in each validator because it is for indian IDs only
- eg. `Aadhaar_IN` or `PAN_IN` and `DRIVING_LC_IN`

**NOTE** : Don't send seperate PRs for each validators please.

**Comment by kehshiba** [comment]
could you assign me? @SwapnilSoni1999

**Comment by SwapnilSoni1999** [comment]
> could you assign me? @SwapnilSoni1999

Sure just now someone finished with Aadhaar and PAN only Driving License validation is remaining
